name = "menu"
name_pretty = "Menu"
fixed_order = true
icon = ""

[[entries]]
icon = ""
text = "Update"
actions = { "update" = "alacritty --class local.floating -e update-perform" }

[[entries]]
icon = ""
text = "Next wallpaper"
actions = { "next-wallpaper" = "theme-bg-next" }

[[entries]]
icon = ""
text = "Capture"
actions = { "capture" = "walker --theme menus -m menus:capture --width 295 --minheight 1 --maxheight 600" }

[[entries]]
icon = ""
text = "Keybindings"
actions = { "keybindings" = "menu-keybindings" }

[[entries]]
icon = "󰐥"
text = "System"
actions = { "system" = "walker --theme menus -m menus:system --width 295 --minheight 1 --maxheight 600" }
