#!/bin/bash

set -e

SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
source "$SCRIPT_DIR/lib/helpers.sh"
DOTFILES_DIR="$HOME/.local/share/dotfiles"

# Set initial theme
log_info "Setting up initial theme (everforest)..."
mkdir -p "$DOTFILES_DIR/current"
ln -snf "$DOTFILES_DIR/themes/everforest" "$DOTFILES_DIR/current/theme"
ln -snf "$DOTFILES_DIR/current/theme/backgrounds/1.png" "$DOTFILES_DIR/current/background"

mkdir -p "$HOME/.config/nvim/lua/plugins"
mkdir -p "$HOME/.config/btop/themes"
mkdir -p "$HOME/.config/mako"
mkdir -p "$HOME/.config/alacritty"
mkdir -p "$HOME/.config/starship/configs"

ln -snf "$DOTFILES_DIR/current/theme/neovim.lua" "$HOME/.config/nvim/lua/plugins/theme.lua"
ln -snf "$DOTFILES_DIR/current/theme/btop.theme" "$HOME/.config/btop/themes/current.theme"
ln -snf "$DOTFILES_DIR/current/theme/mako.ini" "$HOME/.config/mako/config"
ln -snf "$HOME/.config/starship/configs/config-default.toml" "$HOME/.config/starship.toml"

gsettings set org.gnome.desktop.interface color-scheme "prefer-dark"
gsettings set org.gnome.desktop.interface gtk-theme "Adwaita-dark"
gsettings set org.gnome.desktop.interface icon-theme "Yaru-sage"
gsettings set org.gnome.desktop.interface font-name 'JetBrains Mono Nerd Font 11'
gsettings set org.gnome.desktop.interface monospace-font-name 'JetBrains Mono Nerd Font 11'

log_success "Initial theme set (everforest)"
